### ISSUE TITLE
When accessing module declarations from UMD, they must be marked by both @JsModule and @JsNonModule

### ISSUE THREAD

**Issue by Arakash** [samgarasx/kotlin-js-wrappers#3]
With the current Kotlin Version (1.3.70), many samples throw the following error in compileKotlinJs:

> When accessing module declarations from UMD, they must be marked by both @JsModule and @JsNonModule

for Example in practically all the Form Samples, or when using antd.message.message

**Comment by oxiadenine** [comment]
Added compatibility with UMD
