### ISSUE TITLE
bump antd version

### ISSUE THREAD

**Issue by gad2103** [samgarasx/kotlin-js-wrappers#4]
hey thanks for writing this wrapper its been incredibly useful. do you have any plans to bump the version? antd is currently in beta for v5 IIRC and this is pinned to 3.20.x.

**Comment by oxiadenine** [comment]
Hi, I haven't had much time lately since the last update, but yes, the next thing I will do is update Ant Design wrapper to last version

**Comment by gad2103** [comment]
cool. let me know if you want help on that. we could divide and conquer

**Comment by oxiadenine** [comment]
Helping with this would be awesome, I'm going to create Slack to organize ourselves

**Comment by oxiadenine** [comment]
kotlin-antd v4.8.6-pre.5 released
