### ISSUE TITLE
Update wrappers to be compatible with new IR compiler (both mode)

### ISSUE THREAD

**Issue by darizhap** [samgarasx/kotlin-js-wrappers#6]
Is it possible to build and publish current versions of kotlin wrappers in IR-compatible mode to Bintray repository?

**Comment by oxiadenine** [comment]
We are working on Ant Design wrapper update, before it we will add support to the new IR compiler

**Comment by oxiadenine** [comment]
I'm waiting for feedback on this YT issue:
https://youtrack.jetbrains.com/issue/KT-45374

**Comment by oxiadenine** [comment]
The error that shows IntelliJ IDEA persists, but Gradle build seems to be working as expected now.
